---
title: "CodeBook"
author: "Me"
date: "20 June 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Variables

In the final data set there are 80 variables.
These are described below with details of their creation.

# Activity

This is the activity the volunteers were performing when the data was collect.
This was extracted from the "y.txt" dataset for both test and train as a numeric value, and combined.
Using a lookup from the file "activity_lables.txt" this numbers were converted to the activity description.

# Means and Standard Deviations

For the below list of variables, the mean and standard deviation is a column within the dataset.
In the inital data extracted, we had information on all of these at a individual experiment level.
We there avergaed them all within each activity give us the final values.

The names of the variables describe them, with regard to sensors and axis direction (sometimes).

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

